// --- DATA: JUZ 30 SURAHS ---
export const JUZ_30_SURAHS = [
  { id: 78, name: "An-Naba", english: "The Tidings" },
  { id: 79, name: "An-Nazi'at", english: "The Snatchers" },
  { id: 80, name: "Abasa", english: "He Frowned" },
  { id: 81, name: "At-Takwir", english: "The Overthrowing" },
  { id: 82, name: "Al-Infitar", english: "The Cleaving" },
  { id: 83, name: "Al-Mutaffifin", english: "Defrauding" },
  { id: 84, name: "Al-Inshiqaq", english: "The Sundering" },
  { id: 85, name: "Al-Buruj", english: "The Mansions of the Stars" },
  { id: 86, name: "At-Tariq", english: "The Morning Star" },
  { id: 87, name: "Al-A'la", english: "The Most High" },
  { id: 88, name: "Al-Ghashiyah", english: "The Overwhelming" },
  { id: 89, name: "Al-Fajr", english: "The Dawn" },
  { id: 90, name: "Al-Balad", english: "The City" },
  { id: 91, name: "Ash-Shams", english: "The Sun" },
  { id: 92, name: "Al-Lail", english: "The Night" },
  { id: 93, name: "Ad-Duha", english: "The Morning Hours" },
  { id: 94, name: "Ash-Sharh", english: "The Relief" },
  { id: 95, name: "At-Tin", english: "The Fig" },
  { id: 96, name: "Al-Alaq", english: "The Clot" },
  { id: 97, name: "Al-Qadr", english: "The Power" },
  { id: 98, name: "Al-Bayyinah", english: "The Clear Proof" },
  { id: 99, name: "Az-Zalzalah", english: "The Earthquake" },
  { id: 100, name: "Al-Adiyat", english: "The Courser" },
  { id: 101, name: "Al-Qari'ah", english: "The Calamity" },
  { id: 102, name: "At-Takathur", english: "The Rivalry in World Increase" },
  { id: 103, name: "Al-Asr", english: "The Declining Day" },
  { id: 104, name: "Al-Humazah", english: "The Traducer" },
  { id: 105, name: "Al-Fil", english: "The Elephant" },
  { id: 106, name: "Quraish", english: "Quraish" },
  { id: 107, name: "Al-Ma'un", english: "The Small Kindnesses" },
  { id: 108, name: "Al-Kawthar", english: "The Abundance" },
  { id: 109, name: "Al-Kafirun", english: "The Disbelievers" },
  { id: 110, name: "An-Nasr", english: "The Succour" },
  { id: 111, name: "Al-Masad", english: "The Palm Fibre" },
  { id: 112, name: "Al-Ikhlas", english: "The Sincerity" },
  { id: 113, name: "Al-Falaq", english: "The Daybreak" },
  { id: 114, name: "An-Nas", english: "Mankind" },
];

export const THEMES = [
  { id: 'anxiety', label: 'Anxiety & Fear', icon: '🌧️', color: 'from-blue-900 to-slate-900' },
  { id: 'gratitude', label: 'Gratitude (Shukr)', icon: '✨', color: 'from-amber-900 to-slate-900' },
  { id: 'patience', label: 'Patience (Sabr)', icon: '🛡️', color: 'from-emerald-900 to-slate-900' },
];
